### ISSUE TITLE
Minutes and Seconds resetting to 0

### ISSUE THREAD

**Issue by anraiki** [longphanmn/f-datetimerangepicker#3]
I have a Time Range picker and found it strange that we have coding that would remove the minutes and seconds from the initial time. Is there a reason for this?

```
    //Remove minutes and seconds
    initialStartTime = initialStartTime.subtract(Duration(
        minutes: initialStartTime.minute, seconds: initialStartTime.second));
```

```
    initialEndTime = initialEndTime.subtract(Duration(
        minutes: initialEndTime.minute, seconds: initialEndTime.second));
```

**Comment by longphanmn** [comment]
@anraiki I removed minutes and seconds so to prevent this issue of cupertino time picker: initial minute is not divisible by minute interval
